name: simple_searcher

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - DATABASE_URL=sqlite+aiosqlite:///documents.db
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

